on: pull_request
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build Container
        run: make docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
